version: "3.3"
services:
  certificate-signer:
    image: ghcr.io/sunbird-rc/sunbird-rc-certificate-signer
    environment:
      - CONFIG_BASE_PATH=/etc/signer
    ports:
      - "4324:4324"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:4324/health"]
      interval: 30s
      timeout: 10s
      retries: 4
    volumes:
      - ./tests/config:/etc/signer
  test-runner:
    image: ghcr.io/sunbird-rc/python-papermill
    command:
      - "/usr/local/bin/papermill"
      - "--log-output"
      - "/tests/certificate-signer.ipynb"
      - "out"
      - "-p"
      - "host"
      - "certificate-signer"
    volumes:
      - ./:/tests/
